### ISSUE TITLE
Commit Messages for Notebook updates

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#180]
When notebook is created, commit message appearing in revision history should be that the notebook was created. Every time after that when uploading a new version, a field should exist on the modal asking what is different/new with this update.

Also support ability to edit past commit messages.

**Comment by mcrutch** [comment]
Changing old commit messages gets into a REAL mess if it is getting stored in the git repo, so if editing OLD commit messages is actual a requirement they should go in the database.  IF they are going in the database, then just do this as one change with #181 because they touch all of the same items.
Considerations:
Make displaying the field optional? 
One line? Paragraph? 
How will it be displayed? On the revision history page? as an expandable field on the revision history page? only when clicking through to a specific revision?

**Comment by somedave** [comment]
Adding a couple of thoughts:
* I don't know how much people will need to change old commit messages, so if that gets too difficult with the git repo it's probably OK to not worry about it.
* The current commit message should likely be displayed on the notebook view page, with a link to go to the revisions page where all of the previous commit messages are displayed corresponding to their commit ids  (also when you view a specific revision the commit message should be displayed on that view page as well)
* I'd imagine people would use markdown for the commit messages if it's an option, but don't know what you were thinking.  
* In general I see these commit messages less like git style commit updates referring to the code but more like release notes for the potential users of the notebook to understand how the functionality of the notebook might have changed (although I'm sure there's going to be a healthy mix of both)
