### ISSUE TITLE
Star icon and Make Public/Private work but injects a "#" to the url

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#183]
Star icon and Make Public/Private work but injects a "#" to the url AND should also return a success message

**Comment by mcrutch** [comment]
Download icon also adds an octothorpe (#).

**Comment by mcrutch** [comment]
Needed some stuff to fill the day.  Check out branch https://github.com/nbgallery/nbgallery/tree/notebook-actions-change-url
Subscription's "success" is shown by the star changing and the tool tip changing (which now works) rather than a full page load, but you might need to do something extra for Accessibility. All three # problems are fixed.  Might even get a flash message added for Private/public today.  So, mostly done.
