### ISSUE TITLE
Allow to share results (non-stripped notebooks)

### ISSUE THREAD

**Issue by WouterVH** [nbgallery/nbgallery#22]
Sometimes you want to rather share results in your notebook.
In some cases it can take a lot of time to execute the code.

Therefore it would be handy to allow an opt-in feature during notebook-upload
 to not strip cell outputs of a notebook.

**Comment by somedave** [comment]
By default, nbgallery only allows notebooks to be uploaded with output if the notebook is tagged 'trusted' which is a restricted tag that only admins of that nbgallery instance can apply to notebooks - either their own or other users notebooks (relevant code sections [here](https://github.com/nbgallery/nbgallery/blob/16855e465882f6944de5a56ed946f1af06681396/app/controllers/stages_controller.rb#L38) and [here](https://github.com/nbgallery/nbgallery/blob/a3118a3aa23039c5b1e4970b560ef7213114d86e/config/settings.yml#L45) )

That being said, maybe we should make this a configurable option as other use-cases might not be as concerned with users sharing notebooks with output.

I should also note that if you're using our [juptyer docker image](https://github.com/nbgallery/jupyter-docker) we also have that configured by default to strip output of notebooks before they're uploaded.

Finally - if you have your own nbgallery instance up and running and have any feedback/suggestions for us to add to set-up description on the [README](https://github.com/nbgallery/nbgallery/blob/master/README.md) please let us know!

**Comment by kylekyle** [comment]
It's probably worth noting that the trusted notebook feature was added so that we could add examples of what libraries could do within a notebook. The gallery was designed for sharing code, not data. While it's possible to share data, here a few things to look out for: 

First, if you plan to share a lot of data through the gallery then you should probably turn off git versioning. Git doesn't care much for binary. 

Second, including output increases the size of a notebook quickly since notebooks often generate images like graphs and charts. Large notebooks can significantly slow or even crash the renderer. Github gets around that problem by using a JavaScript renderer. 

Finally, remember that notebook output usually includes JavaScript, which can be a security problem especially if you don't trust everyone that will contribute a notebook.

**Comment by timkpaine** [comment]
in our implementation we have a metadata field either "public" or "private". Private has outputs stripped, public does not. we did this because of the reason above, that "trusted" means something different.

**Comment by mcrutch** [comment]
Beyond the "Trusted" notebooks used for small examples, we don't plan to expand further for saving notebook output.  There are just too many avenues for abuse when displaying them within the application.  Even markdown cells are restricted, when displaying in the UI so they don't always render 100% the same in NBGallery, partially for security reasons, but allowing any notebook to display any HTML output in the gallery is just too high of a risk, and sanitizing them like ticket #30 suggest would more than likely break their functionality anyway.  General notebooks with output just can't be reasonably supported in the application in a safe/secure manner.
