### ISSUE TITLE
Add success banner/message when user stars a notebook

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#220]
Left to do from #183. For accessibility reasons, the private/public work just fine as well as subscribing because the success message is a role="alert" which lets screenreading users know when their action worked, we need the same for starring.

**Comment by mcrutch** [comment]
I need to test this, but rather than a full page reload (which subscription also does) can't we just make an element that is screen reader only with role alert that says "You are now (un)subscribed".  Need to get a screen reader to test that, but saves an expensive page reload which potentially causes them to go through the content again

**Comment by mcrutch** [comment]
This is how search filters work, so that should be acceptable, but would need a placeholder element. Then the question is do we want to take away some of those full page reload requiring actions and make them ajax instead?  Right now, star is the only AJAX one, everything else is a full page reload.  Is there a reason for that?
