### ISSUE TITLE
How to use local solr (sunspot)

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#255]
Our nbgallery deployment is small, <1000 notebooks and <1000 users. From what I understand from the docs there's a local 'sunspot' I can use, so it won't be communicating with an external solr (which is causing me problems at the moment). I can't seem to find any docs on how to set that up though. Any ideas?

**Comment by cccs-cat001** [comment]
I found this: https://github.com/nbgallery/nbgallery/blob/master/docs/running.md#startup-sequence
But I get `Errno::EADDRNOTAVAIL (Failed to open TCP connection to localhost:8983 (Cannot assign requested address - connect(2) for "localhost" port 8983))`

**Comment by cccs-cat001** [comment]
I've altered the docker image to run solr before the server, but when I upload a new notebook I get a 404 on `http://localhost:8983/solr/default/update?wt=ruby`. From what I understand this should be working...

**Comment by mcrutch** [comment]
Running local solr is not supported by our published docker container.  It lacks the necessary files.
If you want to run local solr in the docker container you need to build the container yourself after
removing /solr from the .dockerignore
adding config.run-solr="true" to config/environments/production.rb

That SHOULD be enough....but I might have forgotten something.

As for an external solr...yeah...that is a mess...I will try and pull out the files i use for SOLR 8 because sunspot is a really old version.  I run SOLR 8 in prod and dev now.  Mounting into that container is fun at times.

**Comment by mcrutch** [comment]
Actually, let me step that last comment back a bit and do a little bit of digging.  I do want to make it easier for others to run the Solr8 container though.

**Comment by cccs-cat001** [comment]
I think doing what you said won't work because of this line: https://github.com/nbgallery/nbgallery/blob/9ad60fbc38756eb46d8044f623803904d6fc5672/config/initializers/sunspot.rb#L3

Mind you I am by no means a ruby person so I could be way off. I'm going to try what you suggest but also with the thing I found earlier...

**Comment by cccs-cat001** [comment]
So.. I see there is no solr directory in the repo... was I supposed to do some sort of build first and it gets generated? Also I don't see anywhere in the Dockerfile that would copy that over...

**Comment by cccs-cat001** [comment]
Just to be clear, are you recommending I use external solr instead of the built in sunspot? Any tips on getting it to work?

**Comment by mcrutch** [comment]
Local sunspot CAN work, I just remember how it was done in one of our deployments.  I will poke around with it in the morning if I get a chance.

**Comment by mcrutch** [comment]
Poked around this morning, and running sunpot-solr in our current container does not work for a couple reasons:
1) It doesn't have a JRE (I tried installing a JRE and then continuing but then ran into #2)
2) It runs as root inside the container (solr does not like running as root)

For running the stand-alone SOLR container...#55 and #58 relate to this.  I am going to try and clean up the docs (and repo) to support the SOLR 8 container better. (Solr 7 vs Solr 8 are different directory structures)

**Comment by cccs-cat001** [comment]
*Just saw your comment as I was typing this - looks like we were doing the same thing lol*

So I've managed to get solr running inside the container. I added java 8, and I copied all the configs from docker/config/solr into the image. I've made the image run as a user, and I've chown'ed all the files to be owned by said user. All that is working fine, I exec into the container and I see sunspot running for my user, not as root. When I go to upload a notebook, I still get 
```
Error during failsafe response: RSolr::Error::Http - 404 Not Found
Error:     Not Found                                                               
URI: http://localhost:8983/solr/default/update?wt=ruby 
```
Do you know of any way I can test out the URI? Like, I `curl localhost:8983`, and it returns nothing, so I assume it exists?

**Comment by mcrutch** [comment]
That error is because the "core" does not exist in solr. curl localhost:8983 would show you the UI, but one of the things in that output will be that there aren't any cores.  But, Solr doesn't auto create the core because something bad happens when it runs as root and it only half creates things. I even tried creating a solr user in the container as it was running and THEN bringing things up, but some of the config stuff was still missing and it was going down a rabbit hole trying to find it.  I mapped that port to outside of the container and brought it up in a browser and tried to manually create the core and still got nowhere, and to pre-create the files that would be needed for that container to run you would first need an environment with Ruby that worked enough to run solr in the first place and that gets messy (I am going to start doing all development in a container in the future because I don't like ruby being everywhere on my system.

**Comment by cccs-cat001** [comment]
Heyyy!!! I got it to work with the external solr, I had to move the solr/server/solr/default to solr/server/solr/_default, but it works fine after that!

**Comment by mcrutch** [comment]
What version of Solr are you using?

**Comment by mcrutch** [comment]
Closing this out as "local solr not supported in the container" will try to assist with your other ticket.
