### ISSUE TITLE
If the user visits the /lab url to register, send them to lab when they open the notebook.

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#279]
URL is of the format http://{server}/{path-to-juptyer}/lab/tree/name-of-notebook.ipynb
Related code that opens the window: https://github.com/nbgallery/nbgallery/blob/master/app/assets/javascripts/run_in_jupyter.js.erb#L155

(Depends on appropriate extensions being in lab to interface with NBGallery)

**Comment by jeffyjefflabs** [comment]
Just so it's on our radar - Lab has a single document mode that we may want to be the landing spot eventually. Right now the UI is barely different from normal Lab, and I don't think there's a separate URL for it yet, but the plan in Lab 3.0 and beyond is for it to take on some of the use cases of the classic notebook UI.

**Comment by mcrutch** [comment]
Once we know if it is lab or not, it will be easy to swap out that URL to go to the single document interface.

**Comment by mcrutch** [comment]
I have been thinking about this a bit.  There are a couple of options:
1 - Allow the user to pick what UI they want to load as a preference in NBGallery (Lab/Classic)
2 - Have the environment set it (Classic would just not set anything, the lab extension sends a parameter right now that is ignored)
Problem with #1 they end up in a "lab" environment that doesn't have the plugins (or somehow lab is not installed)
Problem with #2 is if they accidentally go to /tree, it might reset it to classic.
Thoughts? @jeffyjefflabs

**Comment by mcrutch** [comment]
Ok, here is my current plan.  
1 - When they first register, if the "user interface" option isn't set, defaults to classic
2 - When they update an environment from the plugins, if the "user interface" option is set, that takes precedence, if it is not set it leaves it as is (if set currently)  If the parameter is sent, and is the current setting is empty, it will set it (This means if they start using lab, it will update to lab)
3 - They can also choose manually
When we migrate to Lab 3.0, an MDI vs SDI distinction can be added as an option with SDI becoming the default most likely.

**Comment by jeffyjefflabs** [comment]
That seems reasonable.  I think most of our users now are Classic users (and would actively prefer Classic over Lab, because they don't need all the IDE-like features) and so I think the priority should be not to accidentally switch them into Lab.  Right now they have to manually change the URL from /tree to /lab - and if I'm interpreting your plan correctly, that would tell nbgallery to change their environment from Classic to Lab, right?  I think that's mostly ok, but (just thinking out loud here) would we want the lab extension to prompt them something like "Would you like to launch notebooks directly into Lab from now on?" (if that's feasible to do without nagging them every time - which probably involves checking what's already set on the nbgallery side).

About choosing manually (your item 3) - I was thinking about that recently, but coming from the other side, from the perspective of the "Run in Jupyter" button.  There are a handful of URLs you might want to launch a notebook into: classic, classic dashboard (the deprecated extension), voila, lab, and lab single doc.  So one thing we might want to do is have a pull-down next to the Run in Jupyter button that lets you go straight into any of those modes (basically just changing the [final url in run_in_jupyter.js](https://github.com/nbgallery/nbgallery/blob/main/app/assets/javascripts/run_in_jupyter.js.erb#L155)).

Taking it a step further though, you could also have a per-notebook configurable destination for the Run in Jupyter button (and probably the text should change based on the default e.g. "Run in Lab", "Launch as dashboard", etc).  The order of precedence would go like this:

 1. Notebook-specific, configured by the author - for example, if a notebook is intended to be a voila dashboard, the author can configure that in nbgallery, and then it would launch users straight into voila when they click Run in Jupyter - and if the user wanted to see the code instead, they could use the pulldown to choose one of the other options.
 2. User-configured preference (item 3) - this would let power users opt into Lab for all other notebooks
 3. Site default - this would stay classic for a while for sure, but if things start to break in classic then we could change the default to lab single doc, while leaving classic in the pulldown as a deprecated option.

I hadn't thought about the interplay with the Environment Registration extension until now though - there would be some corner cases to deal with.  Like if a notebook author set a notebook-specific default to "Run in Lab", you wouldn't want that to cause the Registration extension to change the user's preference from Classic to Lab.

Obviously this is a bigger proposal than just figuring out what the Registration extension should do; just throwing it out there as something to think about - maybe it should be opened as a separate issue.

**Comment by mcrutch** [comment]
Ok, so for registration how about:
- If the environment exists, do not change
- If the environment didn't already exist, set it as appropriate (Lab vs Classic)

User would still have the option to change what UI (classic vs lab) that environment opens in the Environments screen.

Lab SDI vs Lab MDI might be distinct options once we are using Lab 3.0....for now will use Lab MDI URL

Notebook Specific - I don't like this EXCEPT for the voila/dashboard case. But yes, that is a completely different issue.

**Comment by jeffyjefflabs** [comment]
Sounds good to me!
