### ISSUE TITLE
Posting comment does not cause page to reload thus having comment metric update for the notebook

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#318]
Posting comment does not cause page to reload thus having comment metric update for the notebook (which makes people double guess if it really was added successfully).

Also remove the "#" that gets injected in the URL upon posting comment successfully (or perhaps on fails).

**Comment by mcrutch** [comment]
I have not been able to cause the "#" but hooking into this will be awkward because it is all javascript being done by commentator.  Don't want to force reload immediately after the comment, don't want to force reload if no comments have been added.  MIght be some fun javascript as an extra action on close button that tries to figure out what happened.  Pulling in the commontator views looks messy as hell
