### ISSUE TITLE
rails and rack-cors gems are missing from Dockerfile

### ISSUE THREAD

**Issue by phungc** [nbgallery/nbgallery#32]
rails and rack-cors gems are missing from Dockerfile

RUN gem install rails rack-cors

**Comment by jeffyjefflabs** [comment]
What errors are you seeing?  Those should be installed by the [bundle install](https://github.com/nbgallery/nbgallery/blob/master/Dockerfile#L20) line in the Dockerfile.  The [auto build at Docker Hub](https://hub.docker.com/r/nbgallery/nbgallery/builds/) seems to be fine.  Is there a reason you're building the image from scratch instead of using the one from Docker Hub?

**Comment by phungc** [comment]
There was an error with rails was not found when running from pre-built docker image.

**Comment by jeffyjefflabs** [comment]
That fixed the errors I saw - let us know how that works out.

**Comment by phungc** [comment]
Thank you @jeffyjefflabs
