### ISSUE TITLE
Show private notebooks in Group, User, and search listings for Admins

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#339]
Currently admins can see private notebooks in reviews and change requests that don't belong to them, but when looking up a notebook by name, or transferring ownership of notebooks from a group or user to another, etc admins need to be able to see private notebooks in said listings.

For searches can enable it with a checkbox like deprecated?

Current workaround is for the admin to go to each notebook directly via url after returning a list of ids in a MYSQL database call.

**Comment by jeffyjefflabs** [comment]
No objection to this, but just as a bit of background, we've had users notice (from the view stats) and complain when admins are poking around in private notebooks.  So I definitely like the idea of opting in with a checkbox - some of the permission check methods have a `use_admin` parameter that was in anticipation of this sort of thing.  I think it would also be helpful if you can come up with a visual cue in the search listings to distinguish "private notebook I can see because I'm admin" vs "private notebook I can see because I own it."

(Not directly related to the search listings, but you could also suppress click events when admins view private notebooks they don't own - which isn't just being sneaky, it also in theory keeps the recommender stats a little cleaner, although in practice it's probably not much of an effect.)

**Comment by mcrutch** [comment]
So, if this is for an admin function could we just do something similar to the All Users page with notebooks in the admin section that is paginated and filterable so you find find notebooks by the group name, or owner, or name?  Feels less problematic then hacking in a search field only visible to admins and appropriately dealing with SOLR permissions for admins.

**Comment by manfromjupyter** [comment]
Regarding Jeff's comment, I understand the community's concerns, but we wouldn't click in these unless we had a specific need to ex:
- apply deprecation banner to all,
- change ownership to a different user or group or user (so we're not messing directly with the SQL database and admins that don't have access or aren't comfortable with sql can do this)
- return all notebooks using a given thing that would be mentioned in description or title because of an update or alert and needing to let all of these owners know to update their notebooks.

Low priority ticket for sure. I don't think we need to architect something new, but whatever works. These are the pains; whatever solution is easier/safer/whatever , I'm in favor of.

**Comment by mcrutch** [comment]
See branch https://github.com/nbgallery/nbgallery/tree/admin-search for a partial implementation of admin search
Todos in the last commit message.

**Comment by mcrutch** [comment]
Also works for user page
http://<galleryurl>/users/<id>?use_admin=true will also show that user's private notebooks
