### ISSUE TITLE
Keycloak OpenID Connect

### ISSUE THREAD

**Issue by bryaneadams** [nbgallery/nbgallery#342]
Is it possible to add Keycloak OpenID Connect as an additional Oauth login method?

**Comment by kafonek** [comment]
@mcrutch @jeffyjefflabs I'm not working on a PR for this, but wanted to throw out some documentation since I looked at Keycloak a bit.  It should be compatible with OmniAuth, so I think it'll plug right into https://github.com/nbgallery/nbgallery/blob/2cbbde6cff8ac261c5d7df02908e0d5099f96ad0/app/controllers/callbacks_controller.rb#L3.  

There is an OmniAuth-based gemfile for keycloak specifically, https://github.com/ccrockett/omniauth-keycloak.

**Comment by mcrutch** [comment]
My attempts to get keycloak to work without breaking the others failed.  If memory serves it was something about one function wanting an _ one not wanting an _ and the url flip flopping between the two, and it just wasn't worth the headache of trying to sort it out in a generic way.  I will leave this open for a few months if someone else wants to throw up a pull request, but otherwise it will be closed as won't fix.
