### ISSUE TITLE
Cannot login for the same user using different login mechanism 

### ISSUE THREAD

**Issue by alexanghh** [nbgallery/nbgallery#356]
It is possible to allow a user to login via both LDAP (net-ldap) and Keycloak (omniauth)?

I have enabled both LDAP and Keycloak login in my nbgallery. 
I have an account that had first used LDAP (net-ldap) to login (and register). When I tried to login via Keycloak, I am getting the following error: 
"Validation failed: Email has already been taken, Email has already been taken"

Edit:
I solved it by changing app/models/user.rb:
`line 577: create!(user) >> where(:email => info['email']).first_or_create!(user)`
Not sure if this is the ideal approach as I am unfamiliar with ruby. But this should allow for multiple Oauth mechanism.

**Comment by bryaneadams** [comment]
@alexanghh I have been trying to enable KeyCloak login (issue #342 ) Do you mind sharing with me how you enabled login with KeyCloak?

**Comment by alexanghh** [comment]
@bryaneadams In general, you can follow the instructions from https://github.com/ccrockett/omniauth-keycloak.
The specific changes as follows:
File | Line | Changes
------------ | ------------- | ---------------
app/models/user.rb | 8 | omniauthable, omniauth_providers: %i[keycloakopenid]
app/models/user.rb | 577 | where(:email => info['email']).first_or_create!(user)
config/initializers/devise.rb* | 258 | config.omniauth :keycloak_openid, ENV['KEYCLOAK_ID'], ENV['KEYCLOAK_SECRET'], client_options: { site: "https://example.keycloak-url.com", realm: "example-realm" }, :strategy_class => OmniAuth::Strategies::KeycloakOpenId
app/assets/stylesheets/modals.scss | 409 | == add styles for keycloak ==
app/views/devise/shared/_oauthlogin.html.slim | 19 | == add html code for keycloak ==
app/controllers/callbacks_controller.rb | 3 | append "keycloakopenid" to the list of oauth methods

PS: I had to add "provider_ignores_state: true" due to CSRF. YMMV.

**Comment by mcrutch** [comment]
For multiple authentication for the same user...the PROPER way to do this gets a lot more complicated since not all services put the same level of scrutiny into validation of email addresses. So, the proper workflow (which isn't in the plans) would involve somehow asking the user if they want to also allow this other oauth method, but would require a completely different flow and some refactoring.   It would have to put that oauth method in a "pending" state and have the user log in with their other method to allow it.  So, not sure I want to make that line 577 change in the core codebase.  Something to ponder at some point when I have cycles.

As for adding additional oauth providers...the ideal situation makes that easier to do via plugin, and I may look into it (again, pending available cycles)
