### ISSUE TITLE
Unsharing a notebook does not cause it to reindex

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#383]
Results in user still being possibly able to see the notebook in search results, but not the actual notebook. (didn't test as non-admin) but showed up in search results of an admin even when not escalating privileges to use admin status.

**Comment by jeffyjefflabs** [comment]
Good catch.  We call `notebook.save` from the [notebook summary computation](https://github.com/nbgallery/nbgallery/blob/main/app/models/notebook_summary.rb#L87) to trigger a reindex, so that probably covers this up in most cases (plus unsharing is probably rare).  (And that spot in notebook summary should probably just reindex the notebook manually instead of calling save...)
