### ISSUE TITLE
Bulk Upload

### ISSUE THREAD

**Issue by psychemedia** [nbgallery/nbgallery#40]
Is there any way of uploading a large number of notebooks to seed the gallery (for example, a set of notebooks associated with a course),  for example, uploading a set of notebooks in a zip file, perhaps with an associated metadata file, or pulling a set of notebooks in from a github repo?

**Comment by jeffyjefflabs** [comment]
Hm, we don't have anything like that currently, but definitely something to think about.  I saw your blog post about using Selenium - pretty neat!  We actually do have an API, sort of... many of the Rails endpoints will talk JSON if you ask for it (add `Accept: application/json` in the request headers), and our GUI uses jQuery to do that.  But we haven't documented it (but we should) so right now you'd have to sort of reverse engineer it from the Rails code.

So, options as it stands right now:
 * Client side:
   * Use Selenium to automate browser actions
   * Figure out the API and upload programmatically
 * Server side (also requires some reverse engineering):
   * If you're comfortable with Rails, you can write a command line script (or use `rails console`) to create `User` and `Notebook` objects
   * You could drop the `ipynb` files in the cache directory and then script up mysql commands to add directly to the database

**Comment by psychemedia** [comment]
(By the by, here's a [write up](https://blog.ouseful.info/2019/01/28/first-play-with-nbgallery/) of my informal play with nbgallery once I'd got some notebooks uploaded to it.)

**Comment by jeffyjefflabs** [comment]
That's a great walk-through!  Would you mind if we linked to it from our README?

I believe the errors you're seeing with feedback and change requests are because you haven't configured an email server -- you'll see some environment variables in the docker compose file that need to be set.

Also as I alluded to in #41, it occurred to me after reading your post that if you're using our docker image out of the box, it's not really feasible to edit the config file to enable the health metrics, so I made some changes that let you control that with an environment variable.  Those are in the latest version of the docker image (7.8.1 or later).

**Comment by psychemedia** [comment]
Re: the blog post link, please do.

Re: the email server, I had to enable that to allow new user signups (is there a way of starting up `nbgallery` with a default user?) so I know that is working (on creating a new user, I'm emailed a confirmation link). Are there logs anywhere I could look at to try to investigate this further?

Re: the health metrics config - thanks...

**Comment by jeffyjefflabs** [comment]
Interesting, can't think what it would be if not related to the email server.  The exception details should be in the log - `docker/log/nbgallery/production.log`.  Without an email server set up, I see the body of the email then notice of 500 server error due to this:

```
Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for "localhost" port 25):
  app/controllers/notebooks_controller.rb:418:in `feedback'
```

**Comment by jeffyjefflabs** [comment]
@psychemedia thanks for the suggestion for starting up with a default user - just added https://github.com/nbgallery/nbgallery/commit/a8f9f3e0aba62d3b072fc3d75c477404e4c19d7c

**Comment by psychemedia** [comment]
@jeffyjefflabs Great, thanks... That could make like much easier:-)

**Comment by psychemedia** [comment]
I'm guessing that the bulk upload hack I posted may now be simplified by the [`nbgallery` Python API](https://github.com/nbgallery/nbgallery-api-python) (that package is on my -to-play-with list, just not had a chance yet!)

**Comment by mcrutch** [comment]
This is on our radar now, mostly in support of improving test cases for large datasets for query performance and for searching.  Any thoughts on how to best address:
Title?
Description?
I mean, in theory we could say the first markdown cell must have a header and paragraph description that we snag to populate the system for whoever is uploading it.  But does anyone have better ideas?

**Comment by psychemedia** [comment]
Does nbgallery enforce, or at least encourage, conventions about metadata in notebooks?

**Comment by psychemedia** [comment]
An informal convention of the a level 1 header in the first markdown cell would make sense.

For description, you could have either:

- first non-header paragraph in first markdown cell;
- markdown except level 1 header in  first markdown cell;
- if first markdown cell is just the header, then first para or all text from second markdown cell if that appears before first code cell.

Over-ride that if there is proper / formalised metadata in the notebook.

If there is nothing there, fall back to just the filename as the title?

You probably have access to a large collection of notebooks. Maybe churn some stats over them to see what your hit rate would be?

**Comment by mcrutch** [comment]
I have an idea for a nice starting point (because I am running into a situation I need this soon)
I am going to make a script that asks for the username for the creator, possibly an optional second one for owner (which could be a group name?) Private/public, and the path to find ipynb files.
It will go through the directory picking up the notebooks, the title of the notebook will be the filename of the file, the description will probably be some substring from the first markdown cell.  It might even get released as a partial solution at first while I go back and add other features.

**Comment by psychemedia** [comment]
@mcrutch So I don't get the username prompt? Would this be for a CLI utility? I think what I was looking for originally was a button on a gallery page somewhere that would eg let me upload a zip file and or one or more separate notebooks and have them ingested in one go.

**Comment by mcrutch** [comment]
Right now I am working on a backend CLI admin tool to really seed the system because 
1) I want to seed the gallery with VERY large collections of notebooks for stress testing
2) I want to be able to load them as other users
A web-based interface to bulk upload your own notebooks is something we can still explore down the road, but I need something that will let me seed the database at a very large scale across multiple users/groups, and especially that latter part I don't want to poke holes in the authentication scheme or refactor a bunch of code that affects security to try and shoe-horn that in in the near term.

**Comment by mcrutch** [comment]
Still a work in progress but wanted to at least put this in the repo https://github.com/nbgallery/nbgallery/tree/notebook_import
