### ISSUE TITLE
Options to replace local on-disk git repo and notebook storage

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#444]
Storing the notebooks on disk and the way the git repo operates makes it very difficult to horizontally scale NBG and have a zero-downtime environment.  What can be done to rectify this?  Use this ticket to gather ideas.  

NOTE: This is a heavy lift and may not come to fruition but I want to brainstorm ideas to be able explore a more fault tolerant environment that scales better.

Use a document store to store all of them:
Replace the GitRepo class with something that talks to a document store like MongoDB, or store them in ElasticSearch or something.  Generate UUIDs or use built in facility for UUIDs for commit IDs going forward, make a migration path.

Also have to change how staging and final notebooks are saved in this case, but could be made configurable.

Problems:
Still have to deal with ensuring scheduled jobs only run once even if scaled out, so some engineering would be required there as well.

Why not SOLR?  
Not it's intended purpose

Why not just store them in the database?
Also a possible viable option and makes it easier to ensure consistency avoiding the repo not matching the database problem.

Discuss!

**Comment by jeffyjefflabs** [comment]
No objections from me -- after all, the directory is called "cache" because it wasn't originally supposed to be the canonical copy, but then the remote connection to the gitlab we were using turned out to be unreliable, and our only other option at the time was local disk.

I don't have any experience with Elastic.  Mongo is json-centric so that might be a good fit.  Storing documents in MySQL always feels gross to me, but it's doable if you're careful about character encoding, and of course it has the advantage that we're already using it for metadata.  I can't think of any options that you didn't already mention.  After a quick scan of [wikipedia](https://en.wikipedia.org/wiki/Document-oriented_database), maybe CouchDB is another option? (no experience with that either)

I agree the migration path probably isn't too bad, mostly just need to generate commit ids.  We're already using our own diff code, and commit messages can go in the revisions table.  One thing you lose is the potential for more git-centric workflows, like true forks and branches and pull requests -- but that would be a database sync nightmare and a ton of UI work and probably only 0.1% of the userbase would use it anyway, so that's probably not something that was on our radar in the first place.

Depending on what you go with, you could potentially use its full-text indexing to replace Solr, but that's another huge chunk of code to replace.  (Also I don't know how Elastic or Mongo would compare, but MySQL's full-text indexing is not as nice as Solr, in my opinion.)

One pie in the sky idea that doesn't solve this but is kinda related (hey, you said brainstorm) is you could have the idea of "symlink" notebooks where nbgallery isn't responsible for the primary storage.  This wouldn't be the default, but users could opt in if they wanted to maintain their notebook on a gitlab/github but still have it searchable on nbgallery.  Obviously this would have its own long list of challenges not worth getting into here.

**Comment by manfromjupyter** [comment]
I am okay with whatever. I do not have enough expertise with given infrastructures/databases to provide an opinion. I'll test load times and make adjustments to whatever we decide though.

**Comment by mcrutch** [comment]
The most straight forward, least affect to people using NBG right now, path is to make storing them in MySQL a possibility. (but not directly in the revisions table). Unique ID, Type (Staging/change request/Live(now cache)/revision), content.  Then the content could even stay consistent (nbconvert for the git repo, .ipynb for staging/live/change request)

It avoids the problem of adding yet another service to the stack...making an option and abstracting it away in the main code would make it easier to change, and then a job that migrates things?  

That would mean everything that must be retained would be in one place (because SOLR can be rebuilt on demand if that goes down) and would free up a lot of options for fault tolerance, load balancing, etc...

**Comment by jeffyjefflabs** [comment]
Yeah, that's a pretty solid case for MySQL.  Especially since it's just storage -- I think there would have to be a pretty compelling benefit to justify adding another service, like dramatically improved search or something.

**Comment by mcrutch** [comment]
This branch has the code necessary to do this: 
https://github.com/nbgallery/nbgallery/tree/database-save
