### ISSUE TITLE
Request to Save Accepted, Declined, and Cancelled Change Requests

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#480]
Assigning to both of you to discuss. Talked to Crutch but he wants to have the conversation with you about it too.

Currently, after 7 days, I estimate, of a change request being approved, declined, or cancelled the dif these point to get deleted which cause the row of the sql table for change_requests to be deleted.

**Pains/What problems this causes:**
1.) For that information older than 7 days, we as admins and fellow content users have no knowledge of who made the change requests, what they comment, who approved/denied it, what the approver/denier/canceller commented, what revision was from a change request (if that matters), and other general knowledge that comes up that people ask about or want to know about, like a user earlier today.
2.) There are two different link locations we have in the product right now that will hit production next time we merge that will return 404's because they link to these that after 7 days will not longer exist. These locations are in the `/notebook/id/revisions` that link to `change_request/id` when version changes due to a change request and also on the /change_request page linking to the same spot so that people can see the timeline of the change request (multiple comments get confusion, especially with the recent addition of the changelog). In addition, the comment bubbles to date alone aren't readable by screenreaders so wanted to make this more user friendly.

In the database it appears the `reqid` column caries the reference to the dif and this is what we are tryin to clean up and why we delete to date (to my knowledge). Anyway, because this is references as a `UNI` key (assume Unique or foreign key), when this gets cleaned up, it takes the entire row with it. Request is to not delete the row and keep the row of data for our records and make available to the users as it's important information. When the request is approved, declined, or cancelled, the dif is not viewable anyway so don't agree we don't need it.

**Solution?**
Not sure if it's this easy but would just entail deleting the revision wrapped up within the change request without deleting the change request metadata, don't show any "resolved" change requests on individual user's `/change_request` pages after 7 days just so it doesn't get cluttered, but for admins on `/change_requests/all` they will all populate and we can add pagination. Because the ID's will still exist, the records will still be accessible to users that care about the timestamps and comments or what got forgotten and we won't have to tell users to just look through their emails to around 2 years ago for it (if it's even about them).

**Comment by jeffyjefflabs** [comment]
From a high level, I have no objection to keeping change request records indefinitely.  We didn't see a need for them in the beginning, but if customers are trying to see the history and you're linking to them from the revisions page (which is a good idea) then by all means keep them.  They are currently deleted by the [age-off function](https://github.com/nbgallery/nbgallery/blob/e1b271b59a7c01626d21153e961c0fcc20a2dbe4/app/models/change_request.rb#L88) which is called from the [age_off scheduled job](https://github.com/nbgallery/nbgallery/blob/9bf77b0c3d6e96f6db4b6c4f28607a7397e59eee/lib/scheduled_jobs.rb#L107), so you would just need to remove those bits.  However, note that the "proposed content" (i.e. the new copy of the notebook, not just a diff) is stored on disk, so make sure you're comfortable with that directory growing without limit ([this callback](https://github.com/nbgallery/nbgallery/blob/e1b271b59a7c01626d21153e961c0fcc20a2dbe4/app/models/change_request.rb#L11) deletes the file on disk when the database row is removed).

The reqid is not a reference to any other database table.  It's a redundant identifier in the same way `uuid` is for `Notebook` - both are a remnant from our pre-Rails site, which used uuids as the *primary* id for both notebooks and change requests instead of a 1-up counter.  The reqid is used [in the filename](https://github.com/nbgallery/nbgallery/blob/e1b271b59a7c01626d21153e961c0fcc20a2dbe4/app/models/change_request.rb#L45) just like uuid for notebooks.

(In theory you could phase out both change request reqid and notebook uuid, but we didn't want to break URLs at the time (maybe less of an issue by now), and it would require updating the Jupyter-nbgallery integration extensions, so it's not trivial.)

**Comment by mcrutch** [comment]
Right now we don't expose the notebook for cancelled/approved/declined change requests so it is possible we could get rid of the file at that point.  (at the very least for accepted because that is now a revision) Cancelled/declined would be weird because it would keep trying to compare it to the current one, but maybe we should make it eaisier to pull those down and rework them

If we want to keep them around it would be an option defaulting to  off most likely to not change existing behavior.

**Comment by mcrutch** [comment]
So, UUID isn't going anywhere any time soon because of how revisions and other stuff end up working under the covers (ran into problems around database-save due to that).  

So, a couple of options.  When we display metadata about old change requests, is is ONLY the metadata with no access to the notebook once it is approved/denied.

Possible Idea : 
- By default only display pending and recent (30 days) change requests with a "show all" link
- Keep Approved Metadata but delete notebook (If revision tracking is on, it is seen as a revision.  If revision tracking is off, weird to keep it as well)
- Delete Canceled - Just wipe it out.
- Keep Rejected Metadata?
  - And the notebook with a way to download it to try again?
  - Delete the notebook

**Comment by jeffyjefflabs** [comment]
That seems reasonable to me.  I don't have strong feelings either way about deleting the proposed notebook after a rejection.  I guess I would lean delete, since eventually the real version might evolve to the point where the diff between them is useless.

**Comment by mcrutch** [comment]
I can't find a way to download/run the proposed notebook at all, which is screwy and I think we need to fix that. I could just be blind though.
