### ISSUE TITLE
Error uploading/updating notebooks: NoMethodError revision.commit_message for nil:NilClass

### ISSUE THREAD

**Issue by alexanghh** [nbgallery/nbgallery#503]
Hi, 

I am getting errors when uploading or updating notebooks.
The errors are due to revision.commit_message which causes this error: "NoMethodError in NotebooksController#create undefined method `commit_message=' for nil:NilClass"
Not sure if this is due to revision == nil

Thanks

**Comment by manfromjupyter** [comment]
@alexanghh Sorry, to my knowledge, yes. The fix for this is here if it's what I think it is: https://github.com/nbgallery/nbgallery/issues/478.

Just need to either enable revisions on your end or we need to get done commit messages this when there is no revision history.

Will back to you on next week with the fix or when we think we might be able to get that merged to master (shouldn't be too work to fix)

**Comment by alexanghh** [comment]
@manfromjupyter I had the same issue when TRACK_REVISIONS is turned on. Not sure if my testing was complete though. 
I added the "present" check and it seems to work fine. i.e: 
```
if revision.present?
  revision.commit_message=....
end
```

**Comment by manfromjupyter** [comment]
@alexanghh good to know. Glad it's working fine now with that hack. Good to note, will be sure to check that out when making that fix later. We might be forgetting something on out end.
