### ISSUE TITLE
bug in keyword link to notebooks 

### ISSUE THREAD

**Issue by ezhilal** [nbgallery/nbgallery#53]
I realized that the keyword functionality is not working correctly. Some keywords are shown but not linked to any notebooks and an error message is occurring ("Looks like we had an error - sorry!").

**Comment by mcrutch** [comment]
Interesting...I just regenerated the keywords using the script on our dev instance and the cloud doesn't match the links below it (Some words only appear in the lower part).  I found reference to one of those empty keywords in our database pointing to multiple notebooks, but the search doesn't actually use that table in the database and just bounces off SOLR.

**Comment by jeffyjefflabs** [comment]
I'm on my phone so browsing code is annoying but iirc the cloud is the top N keywords but the text list underneath is top 2N, or something like that.  The cloud starts to look bad with more words.

Honestly I'm surprised anyone looks at the keyword page. 🙂

**Comment by mcrutch** [comment]
I think I found the cause.  I think it is a difference in tokenization of words in the  keyword selection code versus the solr tokenization.

**Comment by mcrutch** [comment]
Four options here I can think of
1) scrap keywords entirely
2) make clicking on a keyword not use search and instead use a reference to keywords table, but then you can't search with the keywords
3) Try to make the keywords code use the same stopword/boundaries as SOLR
4) Try to get SOLR to give us Keywords rather than how we do it now (from reading, might not be easy)

**Comment by jeffyjefflabs** [comment]
No objection to scrapping it.  It was supposed to be an option for discovering notebooks but most users just use search anyway.

**Comment by mcrutch** [comment]
We are removing keywords (#297) so this ticket is OBE
