### ISSUE TITLE
Get Metrics from Accessiblity Users by adding more options to User Preferences

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#532]
Example: for vision problems, breakdown into 3 sections, low vision, blind, and contrast issues. Provide our higher contrast options and larger font issues under there and if they select one have a field appear that asks if they have low vision, etc disability or if they just like it.

Similarly, under each of these sections, include the tool we provide, but add an option that says, "I have a low vision disabiliy, etc but I don't need/like the larger font option."

Under the blind section, I want to roll out a new checkbox called, "I am blind but would like to render pages without images and stylsheets to improve load speed." and "I am blind, but still want to render images/stylesheets for my team's sake. In addition, want to include a little visual gui that isn't selectable that has alerts when a page has finished loading just because I still don't see any screenreader be able to provide that information. For our home page that paints and then loads, that would throw another alert that content has rendered but some other components are still loading.

Under the colorblindness section, I want to roll our an option that renders a little button in the bottom right that witches back and for the between rendering the stylesheet and not if they run into a contrast issue. What it will also do is maintain the focus by grabing previous focus before button and applying just after pressing the button click.

Under the low Vision section, the Ultimate Accessibility Mode ticket (#533) could go under the "Low Vision" option (which is the option to dramatically increase the size of the cursors and adds a highlight around it). Also another one that I will file adds more text spacing and some other things that required to support a WCAG 2.1 requirement and will make testing our product faster and something some browser extensions do for users that want to read things more legibly without zooming in.

Should also add sections for hearing, seizures, and cognitive disabilities and just have options for them to volunteer that information about themselves and want to be considered when rolling out future releases.
- Just a side note, I think for seizures could also roll out an option to slow down transitions site wide for all things (couple lines of CSS). Currently most are at 0.25-0.5 seconds to expand collapse but could roll to 1s and make sure others that don't have one do. Could also lighten background colors where necessary (ex. recommended dropdown is no longer a dark blue on white, it's a white on white with just an outline).

ALL of this together allows us to hone in on each of these users by use case and allows us to target people more appropriately for getting feedback. In addition can measure acitive and usage against other users (if it's ethical) to make sure they are able to use the site as quickly or faster than persons without disabilities.

**Comment by mcrutch** [comment]
So, if we start changing user preferences, we should do it a more expandable way, like storing the configs as json in the database or something, because I don't want to add more tiny int colums to the data, it would get maddening.  The problem is migrating current user preferences to new format user preferences.

**Comment by manfromjupyter** [comment]
I can get behind that.. I hate rails migrations

**Comment by mcrutch** [comment]
I don't know why I didn't cancel this ticket when I first saw it.  We are not going to collect any information about a user's disability.  We provide the tooling for them to present NBGallery in a way accessible to welcoming to them but we do NOT need to ask them for medical related information when making those changes. I don't even what those options present, I don't want to imply that someone is using those settings because they have a disability.  Why they chose the settings they chose is their own.
