### ISSUE TITLE
Show cell/line count in Notebook stats

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#534]
From @kafonek:

"I would find it useful to see some basic statistics on cell/line count in the Notebook stats [or in the metadata somewhere]

- total number of code cells in the Notebook
- total number of lines (sum of line count in each cell)
- max number of lines in any cells

Those numbers help set my expectation on how easy or difficult it will likely be to quickly comprehend what a Notebook is doing. I also expect that it will lead to interesting research opportunities that may help form style guidelines in the future."

We can retrieve number of code cells and number of non-code cells and can get the object of the code cell, but haven't tried grabbing the content within. Could try parsing it on upload and storing it, but have a personal desire to add line numbers (that aren't highlightable) to code cells.

**Comment by mcrutch** [comment]
If anything we need to REDUCE how much is in the notebook stats view because that is a huge bottleneck.  This isn't as much of a problem when viewing a single notebook, but when viewing search results/notebook lists, nb_stats gets EXTREMELY inefficient for large datasets (So much so that there is a ticket about this #161)

**Comment by mcrutch** [comment]
Don't know why I didn't just close this last year.
