### ISSUE TITLE
Include more metadata when downloading notebooks

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#567]
Currently, when we download a notebook, we insert some gallery metadata into the metdata section of the notebook's json ([code](https://github.com/nbgallery/nbgallery/blob/main/app/controllers/notebooks_controller.rb#L266-L274)). This is basically just the minimal set of ids and whatnot neccessary for a Jupyter-nbgallery integration to work. Proposal for ticket is to instead insert the rest of gallery metadata that is available from the metadata endpoint ([code](https://github.com/nbgallery/nbgallery/blob/main/app/controllers/notebooks_controller.rb#L222-L252)).

**Comment by mcrutch** [comment]
Use case?  That is very dynamic data that doesn't affect the notebook itself that changes independently of the notebook and is readily available at endpoints.

**Comment by jeffyjefflabs** [comment]
This was from me.  It's not super important.  The custom voila template we use will display some of the metadata, if it's present.  If you launch a notebook from nbgallery into Jupyter, it won't be there and it'll just say display something like "description not available,"  which is fine.  In another project I'm using the voila template to build a dashboard-only standalone docker image, and for that I do use the metadata endpoint.

**Comment by mcrutch** [comment]
Sorry for the long delay. so long as we make it go in gallery metadata since that is stripped on upload I am ok with this. 
hard links to the code we are talking about:
Download api
https://github.com/nbgallery/nbgallery/blob/4c945587b73e17ed0deaf6e04ad6f30d388f1a83/app/controllers/notebooks_controller.rb#L308

metadata api - https://github.com/nbgallery/nbgallery/blob/4c945587b73e17ed0deaf6e04ad6f30d388f1a83/app/controllers/notebooks_controller.rb#L264
