### ISSUE TITLE
migrate_to_database for notebooks misses change requests, staging as well maybe?

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#571]
Revisions make it across, but change requests do not. Check staging as well.

**Comment by mcrutch** [comment]
Ok, revisions, notebooks, and change requests are all migrated now....is there really any reason to move staging since this requires downtime to do the migration to the database?  I think not.   Am I missing anything else? @jeffyjefflabs thoughts?

**Comment by jeffyjefflabs** [comment]
Can't think of anything you missed.  No compelling reason to move staging since those are transient, unless having temp files on disk is problematic for your deployment scenario (maybe in a multi-container load-balancing situation?).  If staging files exist more than a couple minutes then the user probably abandoned the upload - that does happen, but there's no way for the user to "recover" it anyway, so no reason to persist in the database, unless it just makes things easier.
