### ISSUE TITLE
Carry forward Queued Reviews on notebook updates

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#578]
I thought we caught this but appears now. This may be cleaned up automatically as part of our nightly cron job (because I could have sworn we caught this but I don't know for certain and/or starting to to doubt it). Whenever you have queued reviews and then update the version, we are supposed to delete the reviews that had never been touched. If it was claimed or completed, it's useful knowing for historical purposes what versions were working/looked properly. As it relates to Queued notbeooks though, these reviews were never even assigned/claimed, let alone looked at.

Perhaps the proposed solution is to carry queued reviews forward if they aren't reviewed on an older version. Not sure why, for example, a notebook a week old would need a review but updating a few days after would NOT need a review if it was suddenly updated. I would assume the need for a review would still be needed; we might as well save the users from refilling out the form.

**Comment by jeffyjefflabs** [comment]
Yeah, I agree reviews in "queued" status should always point to the latest revision until claimed.  Maybe if status is queued, then revision should just be null?  Then when claimed, set revision to the latest.  Whatever is easiest, I don't think the implementation really matters, we just don't want things to still be in the queue if there's already a newer revision.

If I *complete* a review and then the author updates the notebook, then we should keep the review tied to the older revision, since that's the code I looked at.

If I *claim* a review and then the author updates the notebook before I finish the review, that's kind of tricky and there's probably not a perfect solution.  Maybe something like an email notification to me (the reviewer) that the notebook has been updated, and then I get an option (or am forced?) to update to the latest revision?

**Comment by mcrutch** [comment]
So, since we were talking about having all reviews done possibly enabling other things....what do you do if one review is completed, two are queued, and the notebook updates?  Do you want to try and get all three reviews done on the same revision or do you pull forward the two queued?

**Comment by jeffyjefflabs** [comment]
Hmm that's another tough one, because what if it was a major change, or there have been multiple changes, or the completed review is 6 months old and the queued ones have been sitting there the whole time.  At some point the completed review becomes "historical" and not relevant to current decisions about the notebook.

Maybe the different types of review should be linked together i.e. one super-review (pinned to a revision) that has 3 sub-reviews?  My concern there is that some types of review may not need to be done as frequently, so then does it look weird to have all these partially-completed (super-)reviews?

You could also say if there are queued reviews for an old revision that also has a completed review, then leave them pinned on the old revision, but ALSO re-queue all three review types for the new revision.  That's probably annoying to reviewers if the author keeps making frequent updates.

Maybe this is a thing where there's a bit of human coordination required - like maybe when the author decides they want the super-duper gold star on their notebook, they say ok I need to hold off on updates and make sure I can wrangle all the reviewers to look at it.

I don't know.  I would say let's avoid over-engineering it until how we see people use it in practice, because I feel like we'll find corner cases for whatever business rules we try to implement.

**Comment by manfromjupyter** [comment]
BLOCKED - until users start using it which requires PR #623 as well as tickets #190, 204, and #411.
