### ISSUE TITLE
Support JSON REST Api calls for each page

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#649]
Currently we offer an HTML, text-only view of most every page, but this would be to actually render in HTML.

Example https://{SITE}/notebooks/{ID}/metrics.json is in JSON

Example [h](https://{SITE}/notebooks/{ID}/revisions.json is in HTML. This is what we want to be made JSON.

**Comment by mcrutch** [comment]
Lets take inventory:
Works: 
- notebooks.json
- notebook/<id>.json (sort of but not changing, downloads ipynb)
- notebook/<id>/feedbacks.json (should add notebook as an element here?)
- notebook/<id>/metric.json (should add notebook as an element here?)
- notebook/<id>/metadata.json
- users.json
- users/<1>.json (should I add a "user" element to this with more details rather than just a list of notebooks?)
- environments.json
- tags.json
- tags/<tag>.json
- languages.json
- language/<langage>.json
- groups/<id>,json
- groups.json
- preferences.json
Doesn't work
- notebooks/<id>/revisions.json
- notebooks/recommended.json
- notebooks/shared_with_me.json
- change_request/<id>.json
- change_requests.json
- reviews.json (low priorty)
- reviews/<id>.json (low priorty)
- admin/packages.json (low priority)
- user_preferences.json (don't know that we have to touch this)
