### ISSUE TITLE
Run in Jupyter fails - JupyterHub

### ISSUE THREAD

**Issue by JesperKrogh** [nbgallery/nbgallery#657]
Hi. 

Not sure if this is on the JupyterHub side or on the NBGallery side - The setup works great if the users has spawned a server allready. But if the Jupyterhub is blank - and the user has not visited Jupyterhub  - then it fails with a "Cannot post to the server". Is it the responsibility of Jupyterhub to spawn when posting - with a not started server - or Nbgallerys responsibility to check for spawn and call the spawn url? 

Thanks.

**Comment by mcrutch** [comment]
NBGallery does not have any capability to spawn environments, especially since everyone might have some custom component in their Jupyter/JupyterHub setup.  NBGallery will only work properly if the user has a Jupyter environment that they have authenticated with (or, obviously, if the Jupyter instance is completely not authenticated, but we don't recommend that).
