### ISSUE TITLE
Migration 20210726183045_change_to_utf8_mb4.rb: index unique_schema_migrations doesn't exist

### ISSUE THREAD

**Issue by BrendanPC** [nbgallery/nbgallery#801]
When running the migrations for a fresh install, it breaks on:

`execute "DROP INDEX unique_schema_migrations on schema_migrations"`

because the `unique_schema_migrations` index does not exist. Indeed if I access the database directly, that index is not there, nor do I see it in any of the previous migration files, so I'm not sure where it is supposed to come from.

Is there a missing configuration step that is supposed to be creating that index? I'm a beginner to Ruby on Rails and wasn't sure if this was some built-in default index.

> == 20210726183045 ChangeToUtf8Mb4: migrating =============
> Mysql2::Error: Can't DROP 'unique_schema_migrations'; check that column/key exists

**Comment by mcrutch** [comment]
I wonder if this is an artifact of the migration to Rails 6...I will try and look at this in the next couple of days.

**Comment by mcrutch** [comment]
Ok, this is resolved and I am publishing hte new image now as well.  You may have to start with a completely clean database again to get the migrations to run through smoothly, otherwise you will have to manually create any indexes that were screwed up/missing and start it up again.  But I ran from a completely clean instance with no tables and it finishes the migrations now.
