### ISSUE TITLE
4MB file too large to upload

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#832]
Hi, we have a user trying to upload a notebook, but they're getting a 413 Request Entity Too Large error. They say the notebook is only 4MB, does that sound normal? Is there a way to configure the size nbgallery will allow? 
Thanks

**Comment by mcrutch** [comment]
How are you running NBG?  just our container in puma (rails server)?  Or in passenger? is it behind a proxy (like nginx?)

**Comment by mcrutch** [comment]
BTW - The actual limit should be about ~15MB (per this - https://github.com/nbgallery/nbgallery/blob/main/db/migrate/20210201111838_create_notebook_files.rb#L4)

**Comment by cccs-cat001** [comment]
Hey thanks for the quick response! We're using the helm chart to deploy. I think it may be nginx that's giving us problems..

**Comment by mcrutch** [comment]
`nginx.ingress.kubernetes.io/proxy-body-size: 15m`  [ref](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size)

might also need: `nginx.org/client-max-body-size: "15m"` [ref](https://www.net7.be/blog/article/kubernetes_nginx_ingress_max_upload_size.html)

But since you wrote most of the helm chart.... ;)

**Comment by cccs-cat001** [comment]
Oh I see... probably need to add those 😅

**Comment by cccs-cat001** [comment]
Adding those configs did fix our issue. Thank you :)
